# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: birdwiki.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='birdwiki.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x62irdwiki.proto\"\x1e\n\nServerInfo\x12\x10\n\x08serverId\x18\x01 \x01(\x05\"\x18\n\x08\x42irdName\x12\x0c\n\x04name\x18\x01 \x01(\t\"7\n\x08\x42irdInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65\x64iting\x18\x02 \x01(\x08\x12\x0c\n\x04text\x18\x04 \x01(\t\"&\n\x08\x42irdPage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1c\n\x0c\x43onfirmation\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\">\n\x08UserInfo\x12\r\n\x05\x63rBio\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rpassword_hash\x18\x03 \x01(\t\",\n\tUserLogin\x12\r\n\x05\x63rBio\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t2\xbe\x02\n\x08\x42irdWiki\x12(\n\x08greeting\x12\x0b.ServerInfo\x1a\r.Confirmation\"\x00\x12%\n\tlistBirds\x12\t.BirdName\x1a\t.BirdInfo\"\x00\x30\x01\x12!\n\x07getBird\x12\t.BirdName\x1a\t.BirdInfo\"\x00\x12$\n\ncreateBird\x12\t.BirdName\x1a\t.BirdInfo\"\x00\x12\"\n\x08readBird\x12\t.BirdName\x1a\t.BirdPage\"\x00\x12\"\n\x08\x65\x64itBird\x12\t.BirdName\x1a\t.BirdPage\"\x00\x12&\n\x08saveBird\x12\t.BirdPage\x1a\r.Confirmation\"\x00\x12(\n\ndeleteBird\x12\t.BirdName\x1a\r.Confirmation\"\x00\x32-\n\tLoginUser\x12 \n\x05login\x12\n.UserLogin\x1a\t.UserInfo\"\x00\x62\x06proto3')
)




_SERVERINFO = _descriptor.Descriptor(
  name='ServerInfo',
  full_name='ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='ServerInfo.serverId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=48,
)


_BIRDNAME = _descriptor.Descriptor(
  name='BirdName',
  full_name='BirdName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BirdName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=74,
)


_BIRDINFO = _descriptor.Descriptor(
  name='BirdInfo',
  full_name='BirdInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BirdInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='editing', full_name='BirdInfo.editing', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='BirdInfo.text', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=131,
)


_BIRDPAGE = _descriptor.Descriptor(
  name='BirdPage',
  full_name='BirdPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BirdPage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='BirdPage.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=171,
)


_CONFIRMATION = _descriptor.Descriptor(
  name='Confirmation',
  full_name='Confirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='Confirmation.flag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=201,
)


_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crBio', full_name='UserInfo.crBio', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password_hash', full_name='UserInfo.password_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=265,
)


_USERLOGIN = _descriptor.Descriptor(
  name='UserLogin',
  full_name='UserLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crBio', full_name='UserLogin.crBio', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='UserLogin.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=311,
)

DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
DESCRIPTOR.message_types_by_name['BirdName'] = _BIRDNAME
DESCRIPTOR.message_types_by_name['BirdInfo'] = _BIRDINFO
DESCRIPTOR.message_types_by_name['BirdPage'] = _BIRDPAGE
DESCRIPTOR.message_types_by_name['Confirmation'] = _CONFIRMATION
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['UserLogin'] = _USERLOGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo = _reflection.GeneratedProtocolMessageType('ServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO,
  '__module__' : 'birdwiki_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo)
  })
_sym_db.RegisterMessage(ServerInfo)

BirdName = _reflection.GeneratedProtocolMessageType('BirdName', (_message.Message,), {
  'DESCRIPTOR' : _BIRDNAME,
  '__module__' : 'birdwiki_pb2'
  # @@protoc_insertion_point(class_scope:BirdName)
  })
_sym_db.RegisterMessage(BirdName)

BirdInfo = _reflection.GeneratedProtocolMessageType('BirdInfo', (_message.Message,), {
  'DESCRIPTOR' : _BIRDINFO,
  '__module__' : 'birdwiki_pb2'
  # @@protoc_insertion_point(class_scope:BirdInfo)
  })
_sym_db.RegisterMessage(BirdInfo)

BirdPage = _reflection.GeneratedProtocolMessageType('BirdPage', (_message.Message,), {
  'DESCRIPTOR' : _BIRDPAGE,
  '__module__' : 'birdwiki_pb2'
  # @@protoc_insertion_point(class_scope:BirdPage)
  })
_sym_db.RegisterMessage(BirdPage)

Confirmation = _reflection.GeneratedProtocolMessageType('Confirmation', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMATION,
  '__module__' : 'birdwiki_pb2'
  # @@protoc_insertion_point(class_scope:Confirmation)
  })
_sym_db.RegisterMessage(Confirmation)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'birdwiki_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

UserLogin = _reflection.GeneratedProtocolMessageType('UserLogin', (_message.Message,), {
  'DESCRIPTOR' : _USERLOGIN,
  '__module__' : 'birdwiki_pb2'
  # @@protoc_insertion_point(class_scope:UserLogin)
  })
_sym_db.RegisterMessage(UserLogin)



_BIRDWIKI = _descriptor.ServiceDescriptor(
  name='BirdWiki',
  full_name='BirdWiki',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=314,
  serialized_end=632,
  methods=[
  _descriptor.MethodDescriptor(
    name='greeting',
    full_name='BirdWiki.greeting',
    index=0,
    containing_service=None,
    input_type=_SERVERINFO,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listBirds',
    full_name='BirdWiki.listBirds',
    index=1,
    containing_service=None,
    input_type=_BIRDNAME,
    output_type=_BIRDINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getBird',
    full_name='BirdWiki.getBird',
    index=2,
    containing_service=None,
    input_type=_BIRDNAME,
    output_type=_BIRDINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='createBird',
    full_name='BirdWiki.createBird',
    index=3,
    containing_service=None,
    input_type=_BIRDNAME,
    output_type=_BIRDINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='readBird',
    full_name='BirdWiki.readBird',
    index=4,
    containing_service=None,
    input_type=_BIRDNAME,
    output_type=_BIRDPAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='editBird',
    full_name='BirdWiki.editBird',
    index=5,
    containing_service=None,
    input_type=_BIRDNAME,
    output_type=_BIRDPAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='saveBird',
    full_name='BirdWiki.saveBird',
    index=6,
    containing_service=None,
    input_type=_BIRDPAGE,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteBird',
    full_name='BirdWiki.deleteBird',
    index=7,
    containing_service=None,
    input_type=_BIRDNAME,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BIRDWIKI)

DESCRIPTOR.services_by_name['BirdWiki'] = _BIRDWIKI


_LOGINUSER = _descriptor.ServiceDescriptor(
  name='LoginUser',
  full_name='LoginUser',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=634,
  serialized_end=679,
  methods=[
  _descriptor.MethodDescriptor(
    name='login',
    full_name='LoginUser.login',
    index=0,
    containing_service=None,
    input_type=_USERLOGIN,
    output_type=_USERINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGINUSER)

DESCRIPTOR.services_by_name['LoginUser'] = _LOGINUSER

# @@protoc_insertion_point(module_scope)
