# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loginuser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loginuser.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0floginuser.proto\">\n\x08UserInfo\x12\r\n\x05\x63rBio\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rpassword_hash\x18\x03 \x01(\t\",\n\tUserLogin\x12\r\n\x05\x63rBio\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t2-\n\tLoginUser\x12 \n\x05login\x12\n.UserLogin\x1a\t.UserInfo\"\x00\x62\x06proto3')
)




_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crBio', full_name='UserInfo.crBio', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password_hash', full_name='UserInfo.password_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=81,
)


_USERLOGIN = _descriptor.Descriptor(
  name='UserLogin',
  full_name='UserLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crBio', full_name='UserLogin.crBio', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='UserLogin.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['UserLogin'] = _USERLOGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'loginuser_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

UserLogin = _reflection.GeneratedProtocolMessageType('UserLogin', (_message.Message,), {
  'DESCRIPTOR' : _USERLOGIN,
  '__module__' : 'loginuser_pb2'
  # @@protoc_insertion_point(class_scope:UserLogin)
  })
_sym_db.RegisterMessage(UserLogin)



_LOGINUSER = _descriptor.ServiceDescriptor(
  name='LoginUser',
  full_name='LoginUser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=129,
  serialized_end=174,
  methods=[
  _descriptor.MethodDescriptor(
    name='login',
    full_name='LoginUser.login',
    index=0,
    containing_service=None,
    input_type=_USERLOGIN,
    output_type=_USERINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGINUSER)

DESCRIPTOR.services_by_name['LoginUser'] = _LOGINUSER

# @@protoc_insertion_point(module_scope)
