# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpcFiles import systemstate_pb2 as systemstate__pb2


class SystemStateStub(object):
    """Definição do serviço
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.saveState = channel.unary_unary(
            '/SystemState/saveState',
            request_serializer=systemstate__pb2.StateInfo.SerializeToString,
            response_deserializer=systemstate__pb2.StateConfirmation.FromString,
        )


class SystemStateServicer(object):
    """Definição do serviço
    """

    def saveState(self, request, context):
        """Recebe a página do passarinho
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemStateServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'saveState': grpc.unary_unary_rpc_method_handler(
            servicer.saveState,
            request_deserializer=systemstate__pb2.StateInfo.FromString,
            response_serializer=systemstate__pb2.StateConfirmation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'SystemState', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
