# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemstate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='systemstate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11systemstate.proto\"9\n\tStateInfo\x12\r\n\x05\x63rBio\x18\x01 \x01(\t\x12\x0c\n\x04\x62ird\x18\x02 \x01(\t\x12\x0f\n\x07\x65\x64iting\x18\x03 \x01(\x08\"\"\n\x11StateConfirmation\x12\r\n\x05saved\x18\x01 \x01(\x08\x32<\n\x0bSystemState\x12-\n\tsaveState\x12\n.StateInfo\x1a\x12.StateConfirmation\"\x00\x62\x06proto3')
)




_STATEINFO = _descriptor.Descriptor(
  name='StateInfo',
  full_name='StateInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crBio', full_name='StateInfo.crBio', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bird', full_name='StateInfo.bird', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='editing', full_name='StateInfo.editing', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=78,
)


_STATECONFIRMATION = _descriptor.Descriptor(
  name='StateConfirmation',
  full_name='StateConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='saved', full_name='StateConfirmation.saved', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['StateInfo'] = _STATEINFO
DESCRIPTOR.message_types_by_name['StateConfirmation'] = _STATECONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateInfo = _reflection.GeneratedProtocolMessageType('StateInfo', (_message.Message,), {
  'DESCRIPTOR' : _STATEINFO,
  '__module__' : 'systemstate_pb2'
  # @@protoc_insertion_point(class_scope:StateInfo)
  })
_sym_db.RegisterMessage(StateInfo)

StateConfirmation = _reflection.GeneratedProtocolMessageType('StateConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _STATECONFIRMATION,
  '__module__' : 'systemstate_pb2'
  # @@protoc_insertion_point(class_scope:StateConfirmation)
  })
_sym_db.RegisterMessage(StateConfirmation)



_SYSTEMSTATE = _descriptor.ServiceDescriptor(
  name='SystemState',
  full_name='SystemState',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='saveState',
    full_name='SystemState.saveState',
    index=0,
    containing_service=None,
    input_type=_STATEINFO,
    output_type=_STATECONFIRMATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSTEMSTATE)

DESCRIPTOR.services_by_name['SystemState'] = _SYSTEMSTATE

# @@protoc_insertion_point(module_scope)
